### ISSUE TITLE
How to add row?

### ISSUE THREAD

**Issue by vinniec** [PriestTheBeast/SimpleGUIBuilder#4]
I want to try you builder I can't find any way to add row to the layout.
If I try to add an element directly to the root I got an error and and then the window closes.

**Comment by vinniec** [comment]
Solved, line 152, substitute this:
```
tree_node = values[event][0]
```
with this


```
try:
	tree_node = values[event][0]
except IndexError:
	pass
```
Now work, but i'm not sure I haven't broken anything!

**Comment by PriestTheBeast** [comment]
Supposedly you don't need to add rows, when you add an element it adds a row as needed.

Also, that line is from the event triggered when an element in the Tree is selected, it shouldn't give an error since it would mean somehow an element was selected but then stops existing when it time for the event xD you did make me discover that apparently it's possible to select multiple elements in a Tree with ctrl, something it is not prepared to handle and so doesn't work :)

With such, I have no idea what the problem might be. Send the error given if you still need help.
